# examples/run_dbsi_cli.py

import sys
import argparse
import numpy as np
from time import time
import warnings

# Import from the installed toolbox
try:
    from dbsi_toolbox.utils import load_dwi_data_dipy, save_parameter_maps
    from dbsi_toolbox.model import DBSIModel
except ImportError:
    print("ERROR: Could not import 'dbsi_toolbox'.")
    print("Please ensure the package is installed by running 'pip install -e .' in the root directory.")
    sys.exit(1)

def main():
    """
    Main function to run DBSI fitting from the command line.
    """
    
    # --- 0. Setup Argparse ---
    parser = argparse.ArgumentParser(
        description="Fits the complete DBSI model to DWI data.",
        formatter_class=argparse.RawTextHelpFormatter
    )
    
    # Required Arguments
    req = parser.add_argument_group('Required Arguments')
    req.add_argument('--nii',  type=str, required=True, help="Path to the 4D NIfTI file (.nii.gz)")
    req.add_argument('--bval', type=str, required=True, help="Path to the .bval file")
    req.add_argument('--bvec', type=str, required=True, help="Path to the .bvec file")
    req.add_argument('--mask',   type=str, default=None, help="Path to the 3D mask. If not provided, one is generated automatically.")
    req.add_argument('--out',  type=str, required=True, help="Output directory for the NIfTI maps")

    # Optional Arguments
    opt = parser.add_argument_group('Optional Arguments')
    opt.add_argument('--prefix', type=str, default='dbsi_cli', help="Prefix for output files (default: 'dbsi_cli')")
    opt.add_argument('--method', type=str, default='least_squares', 
                       choices=['least_squares', 'differential_evolution'],
                       help="Optimization algorithm (default: 'least_squares')")
    
    args = parser.parse_args()

    print("="*70)
    print("DBSI Toolbox - 'CLI Style' (Bash) Execution")
    print("="*70)
    print(f"Input NIfTI:  {args.nii}")
    print(f"Input bval:   {args.bval}")
    print(f"Input bvec:   {args.bvec}")
    print(f"Input Mask:   {args.mask or 'Automatic'}")
    print(f"Output Dir:   {args.out}")
    print(f"Output Prefix: {args.prefix}")
    print(f"Fit Method:   {args.method}")
    print("="*70)

    # --- 1. Load Data ---
    print("\n[1/4] Loading data...")
    try:
        data, affine, gtab, mask = load_dwi_data_dipy(
            f_nifti=args.nii,
            f_bval=args.bval,
            f_bvec=args.bvec,
            f_mask=args.mask
        )
    except Exception as e:
        print(f"FATAL ERROR during data loading: {e}", file=sys.stderr)
        sys.exit(1)
        
    # If no mask was provided, the utils function creates one
    # But the 'fit_volume' function has its own internal logic if 'mask' is None.
    # For consistency, we'll pass 'None' if it wasn't specified.
    if args.mask is None:
        mask = None # Let fit_volume create its own mask
    
    # --- 2. Initialize Model ---
    print("\n[2/4] Initializing complete DBSI model...")
    model = DBSIModel()
    print("  ✓ Model configured.")

    # --- 3. Run Fitting ---
    print(f"\n[3/4] DBSI fitting in progress (Method: '{args.method}')...")
    start_time = time()

    with warnings.catch_warnings(record=True) as w:
        warnings.simplefilter("always")
        
        param_maps = model.fit_volume(
            volume=data, 
            bvals=gtab.bvals, 
            bvecs=gtab.bvecs, 
            mask=mask, # Pass the mask (or None)
            method=args.method,
            show_progress=True
        )
    
    end_time = time()
    print(f"\n  ✓ Fitting completed in {end_time - start_time:.2f} seconds.")
    if w:
        print(f"  ! {len(w)} warnings were generated during fitting.")

    # --- 4. Statistics and Saving ---
    print("\n[4/4] Statistics and Saving Maps")
    print("-" * 70)
    
    # For statistics, we need a defined mask
    if mask is None:
        # If the mask was None, we get it from the one generated by the model (based on R2>0)
        # Or better, let's recalculate it to be safe
        b0_mask = gtab.bvals < 50
        b0_volume = np.mean(data[:, :, :, b0_mask], axis=3)
        threshold = np.percentile(b0_volume[b0_volume > 0], 10)
        mask_stats = b0_volume > threshold
    else:
        mask_stats = mask
        
    valid_mask = mask_stats & (param_maps['R2'] > 0)
    
    if not np.any(valid_mask):
        print("WARNING: No voxels were successfully fitted. Skipping statistics.")
    else:
        print("\n📊 STATISTICS (Mean ± Std. Dev. over valid voxels):")
        r2_mean = np.mean(param_maps['R2'][valid_mask])
        print(f"  Fit Quality (Mean R²): {r2_mean:.4f}")

    # Save results
    save_parameter_maps(param_maps, affine, args.out, prefix=args.prefix)
    
    print("\n✓ PROCESSING COMPLETE")
    print("="*70)

if __name__ == "__main__":
    main()